# Generated by Django 5.0.3 on 2024-03-06 15:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=233, verbose_name='Name')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Amount')),
                ('phone', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid', message='Iltimos Togri kiriting :)', regex='^\\+998\\d{9}$')], verbose_name='Phone')),
                ('type', models.CharField(choices=[('jismon', 'Jismoniy Shaxs'), ('yuridik', 'Yuridik Shaxs')], default='jismon', max_length=50, verbose_name='Type')),
                ('status', models.CharField(choices=[('new', 'New'), ('cancelled', 'Canceled'), ('moderation', 'Moderation'), ('active', 'Active')], default='new', max_length=255, verbose_name='Status')),
                ('company_name', models.CharField(blank=True, max_length=233, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=233, verbose_name='Student Name')),
                ('phone', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid', message='Iltimos Togri kiriting :)', regex='^\\+998\\d{9}$')], verbose_name='Phone')),
                ('contract', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Contract')),
                ('type', models.CharField(choices=[('baklavr', 'baklavr'), ('magestr', 'magestr'), ('asperant', 'asperant')], default='baklavr', max_length=50, verbose_name='Type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=233, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AllocatedAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Amount')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sponsor_amounts', to='common.sponsor', verbose_name='Sponsor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sponsor_amounts', to='common.student', verbose_name='Student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='student',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='common.university', verbose_name='University'),
        ),
    ]
