# Generated by Django 5.0.3 on 2024-03-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_sponsor_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocatedamount',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='student_amounts'),
        ),
    ]
